# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpass < Formula
  desc "CLI toolkit for secret sharing, encryption, mnemonics, and multi-chain key derivation."
  homepage ""
  version "1.6.2"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.2/dpass_1.6.2_darwin_amd64.tar.gz"
      sha256 "d6f7c0930ff40872a67d5de291b8dc5c8b2213d93719e0e9a8d519c257b0807a"

      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.2/dpass_1.6.2_darwin_arm64.tar.gz"
      sha256 "814c0b6362dac0d1dc33612ea4c1dc6d2ef227a797cb2f9b2cca0c5b7b962be0"

      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.2/dpass_1.6.2_linux_amd64.tar.gz"
      sha256 "90b6a27d6bf8bd2ed99cdf174cc6f33ace40800e6d6585e53dfeae468625881f"
      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.2/dpass_1.6.2_linux_arm64.tar.gz"
      sha256 "39a6c56ff46e6e5a86bfe4f43f4476488251cc9801e8d765f65c247ce957639d"
      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dpass --version")
  end
end
