# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpass < Formula
  desc "CLI toolkit for secret sharing, encryption, mnemonics, and multi-chain key derivation."
  homepage ""
  version "1.6.1"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.1/dpass_1.6.1_darwin_amd64.tar.gz"
      sha256 "b6f3214b22fcb65f90b33df0f50e5323930b2d03b94a27aa38c1359cf1aad815"

      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.1/dpass_1.6.1_darwin_arm64.tar.gz"
      sha256 "072a7c0b9d976b4c2ea12156fc8ab6d26f8ad807e2dc6dfdbdb95c9ee9df4d6b"

      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.1/dpass_1.6.1_linux_amd64.tar.gz"
      sha256 "8ce9db7d2cdaf1bccf9669f4597817d8f237ef53e3e6159d3c9f31a229d0ecfd"
      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.1/dpass_1.6.1_linux_arm64.tar.gz"
      sha256 "73163230d216511b383fc0f600ca44043e1ab1178388c0f81a776d037ea1c7d0"
      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dpass --version")
  end
end
