# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpass < Formula
  desc "CLI toolkit for secret sharing, encryption, mnemonics, and multi-chain key derivation."
  homepage ""
  version "1.6.3"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.3/dpass_1.6.3_darwin_amd64.tar.gz"
      sha256 "0085b3d1774dd0a718b200f630b2ceac793120db9524c33b0811dd9b534bdba5"

      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.3/dpass_1.6.3_darwin_arm64.tar.gz"
      sha256 "590f1cefd6e1079d783e56486f7f6e75c5374e1695222bcb3499f789278d267b"

      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.3/dpass_1.6.3_linux_amd64.tar.gz"
      sha256 "5155e3919a4dba8fb4b31d6fc9d14415c775b16d95910cbca779a8c2962f3a7e"
      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbee3u/dpass/releases/download/v1.6.3/dpass_1.6.3_linux_arm64.tar.gz"
      sha256 "293d2d967acd2981c3433ae84d06a910b99477227e8ed936c96996b8ac8b36f1"
      define_method(:install) do
        bin.install "dpass"
        generate_completions_from_executable(bin/"dpass", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dpass --version")
  end
end
